import React from 'react';
import { motion } from 'framer-motion';
import { Shield, FileText, AlertTriangle, ArrowLeft } from 'lucide-react';

type LegalPage = 'privacy' | 'terms' | 'ai-disclaimer';

const CONTENT: Record<LegalPage, { title: string; sections: { heading: string; body: string }[] }> = {
  privacy: {
    title: 'Privacy Policy',
    sections: [
      {
        heading: 'Data we collect',
        body: 'Account identifiers (username mapped to Firebase Auth), research dossiers you save, usage statistics (XP, rank), notebook entries, and optional payment metadata processed by Razorpay. We do not sell personal data.',
      },
      {
        heading: 'How data is stored',
        body: 'Cloud data is stored in Google Firebase (Firestore and Authentication) with security rules restricting access to your account. Local-only mode may store data in your browser when Firebase is unavailable in development.',
      },
      {
        heading: 'Third-party services',
        body: 'AI requests are processed through Google Gemini and Groq when you use cloud intelligence. Spotify integration, when enabled, communicates directly with Spotify. Payment processing uses Razorpay.',
      },
      {
        heading: 'Your rights',
        body: 'You may delete your account and associated dossiers using the in-app Nuclear Purge / account deletion flow. Contact the operator for data export requests where required by law.',
      },
      {
        heading: 'Contact',
        body: 'For privacy inquiries, contact the COGNAPSE operator through the repository or deployment contact channel listed on cognapse.vercel.app.',
      },
    ],
  },
  terms: {
    title: 'Terms of Service',
    sections: [
      {
        heading: 'Acceptance',
        body: 'By using COGNAPSE you agree to these terms. If you do not agree, do not use the service.',
      },
      {
        heading: 'Service description',
        body: 'COGNAPSE provides AI-assisted research synthesis tools. Outputs are generated by third-party language models and may contain errors, omissions, or bias.',
      },
      {
        heading: 'Accounts',
        body: 'You are responsible for safeguarding your credentials. You must not share accounts, abuse rate limits, or attempt to bypass premium or security controls.',
      },
      {
        heading: 'Payments',
        body: 'Premium subscriptions are billed through Razorpay. Refund policies follow applicable consumer law and Razorpay merchant terms unless otherwise stated at purchase.',
      },
      {
        heading: 'Acceptable use',
        body: 'Do not use COGNAPSE for unlawful surveillance, harassment, automated scraping at scale, or generating content that violates applicable law. We may suspend access for abuse.',
      },
      {
        heading: 'Limitation of liability',
        body: 'COGNAPSE is provided as-is without warranties. The operator is not liable for decisions made based on AI-generated research.',
      },
    ],
  },
  'ai-disclaimer': {
    title: 'AI Disclaimer',
    sections: [
      {
        heading: 'Not professional advice',
        body: 'COGNAPSE outputs are not legal, medical, financial, or security advice. Consult qualified professionals before acting on high-stakes decisions.',
      },
      {
        heading: 'Accuracy',
        body: 'Models can hallucinate citations, statistics, and narratives. Always verify claims against primary sources.',
      },
      {
        heading: 'Bias and perspective',
        body: 'Synthesis reflects training data and prompt framing. Use Thought Replay, source lists, and opposing viewpoints when available.',
      },
      {
        heading: 'Sensitive topics',
        body: 'Do not rely solely on AI for intelligence about individuals, classified operations, or real-time crisis response.',
      },
    ],
  },
};

export default function LegalPages({ page, onBack }: { page: LegalPage; onBack: () => void }) {
  const content = CONTENT[page];
  const Icon = page === 'privacy' ? Shield : page === 'terms' ? FileText : AlertTriangle;

  return (
    <div className="min-h-full overflow-y-auto px-6 py-16 max-w-3xl mx-auto">
      <button
        onClick={onBack}
        className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.3em] text-my-muted hover:text-my-accent mb-10"
      >
        <ArrowLeft size={14} /> Back
      </button>
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-4 mb-8">
          <div className="p-3 border border-my-border bg-my-callout/30">
            <Icon size={22} className="text-my-accent" />
          </div>
          <h1 className="text-3xl font-serif font-bold tracking-tight">{content.title}</h1>
        </div>
        <p className="text-[10px] uppercase tracking-[0.2em] text-my-muted mb-10">
          Last updated: May 2026
        </p>
        <div className="space-y-8">
          {content.sections.map((section) => (
            <section key={section.heading}>
              <h2 className="text-sm font-black uppercase tracking-[0.2em] text-my-ink mb-3">
                {section.heading}
              </h2>
              <p className="text-sm leading-relaxed text-my-muted">{section.body}</p>
            </section>
          ))}
        </div>
      </motion.div>
    </div>
  );
}
