import React, { useState, Suspense } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import type { COGNAPSE_Output, ResearchVisibility } from '../types';
import { ShieldAlert, Info, AlertTriangle, ArrowRight, CheckCircle2, Link2, Clock, Download, Search, Lock, Loader2, Share2, Copy, Eye, Globe2, FileText, Code2, ExternalLink, X, BookOpen, GraduationCap, Building2, Shield, CalendarDays, Hash } from 'lucide-react';
import { toast } from '../utils/toast';
import { ErrorBoundary } from './ui';
import clsx from 'clsx';
import { formatAllCitations, getDomainBadge, getDaysSincePublished, getDaysLabel, stripCitationMarkers, type CitationFormat } from '../utils/citations';

/** Download helper for generated text-based exports */
function downloadAsFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Generate a Markdown export from the report */
function generateMarkdown(report: COGNAPSE_Output): string {
  const lines: string[] = [];
  lines.push(`# ${report.query_understood || 'Research Report'}`);
  lines.push('');
  if (report.summary?.bottom_line) {
    lines.push('## Bottom Line');
    lines.push(report.summary.bottom_line);
    lines.push('');
  }
  if (report.summary?.full_synthesis) {
    lines.push('## Full Synthesis');
    lines.push(report.summary.full_synthesis);
    lines.push('');
  }
  if (report.scores) {
    lines.push('## Scores');
    lines.push(`- Credibility: ${report.scores.overall_credibility}`);
    lines.push(`- Relevance: ${report.scores.overall_relevance}`);
    lines.push(`- Consensus: ${report.scores.evidence_consensus}`);
    lines.push('');
  }
  if (report.sources && report.sources.length > 0) {
    lines.push('## Sources');
    report.sources.forEach(s => {
      lines.push(`- ${s.title} (${s.domain}) — Credibility: ${s.credibility_score}`);
    });
    lines.push('');
  }
  if (report.conflicts && report.conflicts.length > 0) {
    lines.push('## Conflicts');
    report.conflicts.forEach(c => {
      lines.push(`- ${c.claim_a} vs ${c.claim_b}: ${c.explanation}`);
    });
    lines.push('');
  }
  if (report.timeline_events && report.timeline_events.length > 0) {
    lines.push('## Timeline');
    report.timeline_events.forEach(t => {
      lines.push(`- ${t.date}: ${t.title}`);
    });
    lines.push('');
  }
  lines.push('---');
  lines.push('*Generated by COGNAPSE | Premium Export*');
  return lines.join('\n');
}

/** Generate a JSON export from the report */
function generateJSON(report: COGNAPSE_Output, citations?: string): string {
  const exportObj: Record<string, unknown> = {
    title: report.query_understood || 'Research Report',
    generated_at: new Date().toISOString(),
    provider: report.provider || 'unknown',
    summary: report.summary,
    scores: report.scores,
    sources: report.sources,
    conflicts: report.conflicts,
    bias_alert: report.bias_alert,
    swot: report.swot,
    timeline_events: report.timeline_events,
    actionable_takeaways: report.actionable_takeaways,
    follow_up_suggestions: report.follow_up_suggestions,
    intelligence_map: report.intelligence_map,
  };
  if (citations) {
    exportObj.references_formatted = citations;
  }
  return JSON.stringify(exportObj, null, 2);
}
// Map rendering removed per request
const PhysicsMap = React.lazy(() => import('./PhysicsMap'));
import { useStore } from '../store';
import confetti from 'canvas-confetti';

import BrandLogo from './BrandLogo';
import ThoughtReplayEngine from './ThoughtReplayEngine';
import PremiumExportModal from './PremiumExportModal';
import SourceDrawer from './SourceDrawer';
import EvidencePreview from './EvidencePreview';


import { generatePremiumPDF } from '../utils/pdfGenerator';
import { dbService } from '../services/dbService';

export default function ReportView({
  report,
  onSubSearch,
  onChatFollowUp,
  readOnly = false
}: {
  report: COGNAPSE_Output,
  onSubSearch: (q: string) => void,
  onChatFollowUp?: (q: string) => void,
  readOnly?: boolean
}) {
  
  const safeText = (val: any) => {
    if (typeof val === 'string') return val;
    if (val === null || val === undefined) return "";
    return JSON.stringify(val);
  };
  const hasConflicts = report.conflicts && report.conflicts.length > 0;
  const hasBias = !!report.bias_alert;
  const [rated, setRated] = useState(false);
  // Use a unique citation instance key (paragraphIdx-partIdx) instead of just source ID
  // to prevent duplicate EvidencePreview panels from stacking when the same source is cited multiple times
  const [hoveredCitation, setHoveredCitation] = useState<string | null>(null);
  const { updateGamification, user, setAuthOpen, deepResearch } = useStore();
  const [isExportModalOpen, setIsExportModalOpen] = useState(false);
  const [generatingPDF, setGeneratingPDF] = useState(false);
  const [shareVisibility, setShareVisibility] = useState<ResearchVisibility>('unlisted');
  const [shareLink, setShareLink] = useState("");
  const [sharing, setSharing] = useState(false);
  const [citationFormat, setCitationFormat] = useState<CitationFormat>('apa');
  const [liveSource, setLiveSource] = useState<{ title: string; url: string } | null>(null);
  // Build a lookup of sourceId → worst citation verdict for display
  const verdictMap = new Map<number, { verdict: string; confidence: number }>();
  if (report.citation_verifications) {
    for (const v of report.citation_verifications) {
      const existing = verdictMap.get(v.source_id);
      // Keep the "worst" verdict (supported < partial < unrelated/contradicted)
      const rank = { supported: 0, partial: 1, unrelated: 2, contradicted: 2 };
      const newRank = rank[v.verdict] ?? 0;
      const oldRank = existing ? (rank[existing.verdict as keyof typeof rank] ?? 0) : -1;
      if (!existing || newRank > oldRank) {
        verdictMap.set(v.source_id, { verdict: v.verdict, confidence: v.confidence });
      }
    }
  }

  const reportId = report.id || report.query_understood;
  const isUnlocked = !!user?.premium;

  const handleCreateShare = async () => {
    if (!user) {
      setAuthOpen(true);
      return;
    }
    setSharing(true);
    try {
      const researchId = report.id || crypto.randomUUID();
      const shared = await dbService.createSharedResearch({
        ownerId: user.id,
        ownerName: user.username,
        researchId,
        report: { ...report, id: researchId },
        visibility: shareVisibility
      });
      const url = `${window.location.origin}/share/${shared.id}`;
      setShareLink(url);
      await navigator.clipboard?.writeText(url);
    } catch (err) {
      console.error("Failed to create share link:", err);
      toast.error("Unable to create share link. Please try again.");
    } finally {
      setSharing(false);
    }
  };

  const handleDownloadPDF = async () => {
    if (!isUnlocked) {
      setIsExportModalOpen(true);
      return;
    }

    setGeneratingPDF(true);
    try {
      await generatePremiumPDF({
        query: report.query_understood,
        report: report,
        deepThesis: report.deep_research || null,
        aiProvider: report.provider || 'gemini'
      });
      if (user) {
        await useStore.getState().addExport({
          id: crypto.randomUUID(),
          userId: user.id,
          researchId: reportId,
          exportType: report.deep_research ? 'deep' : 'normal',
          aiProvider: report.provider || 'gemini',
          query: report.query_understood,
          timestamp: new Date().toISOString()
        });
      }
    } catch (err) {
      console.error(err);
      toast.error("Error packaging PDF. Please try again.");
    } finally {
      setGeneratingPDF(false);
    }
  };

  const handleRating = (rating: number) => {
    if (rated) return;
    setRated(true);

    if (rating >= 4) {
      updateGamification({ xpAcquired: 20 });
      confetti({
        particleCount: 100,
        spread: 60,
        origin: { y: 0.8 },
        colors: ['#F27D26', '#2A4365', '#E2E8F0']
      });
    }
  };

  let normalizedSuggestions = report.follow_up_suggestions || [];
  if (normalizedSuggestions.length === 1 && typeof normalizedSuggestions[0] === 'string' && normalizedSuggestions[0].trim().startsWith('[')) {
    try {
      normalizedSuggestions = JSON.parse(normalizedSuggestions[0]);
    } catch(e) {}
  }

  // Aggressive normalization to handle AI hallucinating objects instead of strings
  normalizedSuggestions = normalizedSuggestions.map((s: any) => {
    if (typeof s === 'string') return s;
    if (typeof s === 'object' && s !== null) {
      return s.question || s.text || s.suggestion || s.query || Object.values(s)[0] || JSON.stringify(s);
    }
    return String(s);
  }).filter(Boolean);

  return (
    <div className="w-full flex flex-col animate-in fade-in slide-in-from-bottom-4 duration-700 pb-16">
      
      {/* Header & Badges */}
      {report.gamification?.badge_unlocked && (
         <div className="mb-4 inline-flex items-center gap-3 px-4 py-2 bg-my-score border border-my-accent/20 rounded-[2px] text-my-accent animate-bounce w-fit">
           <span className="text-xl">{report.gamification.badge_unlocked.icon}</span>
           <div>
             <p className="text-xs font-bold uppercase tracking-widest leading-none">Badge Unlocked: {report.gamification.badge_unlocked.name}</p>
           </div>
         </div>
      )}

      {/* Query Title & Brand */}
      <div className="mb-8">
        <div className="flex items-start justify-between gap-8 mb-6">
          <h1 className="font-serif text-[32px] leading-[1.1] text-my-ink flex-1">
            {safeText(report.query_understood)}
          </h1>
          <BrandLogo size={44} />
        </div>
        {(() => {
          const clusters = new Set(report.sources?.map(s => s.domain?.split('.').slice(-2).join('.')).filter(Boolean));
          const coverageDepth = `Coverage: ${report.sources?.length || 0} sources across ${clusters.size} domains`;
          return (
            <div className="text-[9px] text-my-muted font-mono mb-4 tracking-wider">
              {coverageDepth}{report.conflicts?.length ? ` · ${report.conflicts.length} conflict${report.conflicts.length > 1 ? 's' : ''} detected` : ''}
            </div>
          );
        })()}

        {/* Unified Action Bar */}
        <div className="flex flex-wrap items-center gap-3 mb-6 pb-4 border-b border-my-border">
          {!readOnly && (
            <div className="flex items-center gap-2 p-1.5 border border-my-border bg-my-callout min-touch-h">
              <select
                id="share-visibility"
                name="share-visibility"
                value={shareVisibility}
                onChange={(e) => setShareVisibility(e.target.value as ResearchVisibility)}
                className="bg-transparent text-[9px] font-black uppercase tracking-widest text-my-ink focus:outline-none"
              >
                <option value="private">Private</option>
                <option value="unlisted">Unlisted</option>
                <option value="public">Public</option>
              </select>
              <button
                onClick={handleCreateShare}
                disabled={sharing}
                className="px-3 py-2 md:px-3 md:py-2 px-4 py-3 bg-my-ink text-white dark:bg-my-accent dark:text-black text-[9px] font-black uppercase tracking-widest flex items-center gap-2 disabled:opacity-50"
              >
                {sharing ? <Loader2 size={12} className="animate-spin" /> : <Share2 size={12} />}
                Share
              </button>
            </div>
          )}

          {!readOnly && (
            <div className="flex items-center gap-1.5 text-[8px] text-my-muted font-mono">
              <Info size={10} />
              <span>Preview feature</span>
            </div>
          )}

          <div className="flex-1" />

          <div className="flex items-center gap-2">
            {isUnlocked && (
              <>
                <button
                  onClick={() => {
                    const md = generateMarkdown(report) + '\n\n---\n\n## References (' + citationFormat.toUpperCase() + ')\n\n' + (report.sources ? formatAllCitations(report.sources, citationFormat) : 'No sources available.');
                    downloadAsFile(md, `${report.query_understood?.substring(0, 40).replace(/[^a-zA-Z0-9]/g, '_') || 'report'}.md`, 'text/markdown');
                    toast.success('Markdown report downloaded.');
                  }}
                  className="px-3 py-2.5 text-[8px] font-black uppercase tracking-widest transition-all border border-my-border hover:border-my-accent bg-my-callout text-my-ink flex items-center gap-1.5"
                  title="Export as Markdown"
                >
                  <FileText size={11} /> .md
                </button>
                <button
                  onClick={() => {
                    const citations = report.sources ? formatAllCitations(report.sources, citationFormat) : '';
                    const json = generateJSON(report, citations);
                    downloadAsFile(json, `${report.query_understood?.substring(0, 40).replace(/[^a-zA-Z0-9]/g, '_') || 'report'}.json`, 'application/json');
                    toast.success('JSON export downloaded.');
                  }}
                  className="px-3 py-2.5 text-[8px] font-black uppercase tracking-widest transition-all border border-my-border hover:border-my-accent bg-my-callout text-my-ink flex items-center gap-1.5"
                  title="Export as JSON"
                >
                  <Code2 size={11} /> .json
                </button>
                {/* Citation format selector */}
                <div className="flex items-center gap-1 px-2 py-2 border border-my-border bg-my-callout">
                  <BookOpen size={10} className="text-my-muted" />
                  <select
                    id="citation-format"
                    name="citation-format"
                    value={citationFormat}
                    onChange={(e) => setCitationFormat(e.target.value as CitationFormat)}
                    className="bg-transparent text-[8px] font-black uppercase tracking-widest text-my-ink focus:outline-none"
                  >
                    <option value="apa">APA</option>
                    <option value="mla">MLA</option>
                    <option value="chicago">Chicago</option>
                  </select>
                </div>
              </>
            )}
            <button
              onClick={handleDownloadPDF}
              disabled={generatingPDF}
              className={clsx(
                "px-5 py-2.5 text-[9px] font-black uppercase tracking-widest transition-all shadow-lg flex items-center gap-2",
                isUnlocked 
                  ? "bg-green-600 hover:bg-green-700 text-white hover:scale-105" 
                  : "bg-my-accent hover:bg-my-accent/90 text-white dark:text-black hover:scale-105"
              )}
            >
              {generatingPDF ? (
                <>
                  <Loader2 size={12} className="animate-spin" /> Compiling Dossier...
                </>
              ) : isUnlocked ? (
                <>
                  <Download size={12} /> Premium Report
                </>
              ) : (
                <>
                  <Lock size={12} /> Unlock Full Report
                </>
              )}
            </button>
          </div>
        </div>

        {/* Share link — appears right after the action bar when generated */}
        {shareLink && (
          <div className="mb-4 p-3 border border-my-border bg-my-bg flex flex-col sm:flex-row sm:items-center gap-3 justify-between">
            <div className="flex items-center gap-2 min-w-0">
              <Eye size={14} className="text-my-accent shrink-0" />
              <span className="text-[10px] font-bold text-my-muted uppercase tracking-widest shrink-0">Read-only link copied</span>
              <span className="text-[11px] text-my-ink truncate">{shareLink}</span>
            </div>
            <button
              onClick={() => navigator.clipboard?.writeText(shareLink)}
              className="text-[9px] font-black uppercase tracking-widest text-my-accent flex items-center gap-1.5"
            >
              <Copy size={11} /> Copy
            </button>
          </div>
        )}

        {readOnly && (
          <div className="mb-4 p-3 border border-my-border bg-my-callout flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-my-muted">
            <Globe2 size={13} className="text-my-accent" /> Public read-only research view
          </div>
        )}

        {/* Bottom Line */}
        <div className="bg-my-callout border-l-[4px] border-my-accent px-6 py-5 italic font-serif text-[15px] leading-[1.6] text-my-ink">
          {safeText(stripCitationMarkers(report.summary?.bottom_line || '')) || "Summary not available for this report."}
        </div>

        {!isUnlocked && (
          <p className="text-[9px] text-my-muted font-mono text-center border-t border-my-border pt-3 mt-1">
            What did the other AI models find? Consensus scores, reasoning layers &amp; strategic intel — <strong>locked in Premium</strong>
          </p>
        )}
      </div>

      <motion.div
        initial="hidden"
        animate="visible"
        variants={{ visible: { transition: { staggerChildren: 0.06 } } }}
        className="flex flex-col lg:grid lg:grid-cols-[1fr_0.85fr] gap-[24px] min-w-0"
      >
        
        {/* Synthesis Column */}
        <motion.div
          variants={{ hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0 } }}
          className="flex flex-col gap-6 min-w-0"
        >
          <SectionTitle>Intelligence Synthesis</SectionTitle>
          
          {(report.summary?.full_synthesis || report.summary?.eli5_version) && (
            <div className="bg-my-bg/70 backdrop-blur-md p-6 border border-my-border rounded-[4px] text-[13px] leading-[1.6] text-my-syn flex flex-col gap-4 shadow-sm">
              {report.summary?.eli5_version && (
                <div className="p-4 bg-my-accent/5 border border-my-accent/10 rounded">
                  <span className="font-bold text-[10px] uppercase tracking-widest block mb-1 text-my-accent">ELI5 Version</span>
                  {safeText(stripCitationMarkers(report.summary.eli5_version))}
                </div>
              )}
              {report.summary?.full_synthesis && (
                <div className="text-[14px] leading-[1.7] text-my-syn space-y-[1.25em]">
                  {report.summary.full_synthesis.split('\n').map((para: string, i: number) =>
                    para.trim() ? (
                      <p key={i} className="leading-[1.7] group relative">
                        {(() => {
                          const parts = para.split(/(\[\d+\])/g);
                          return parts.map((part: string, j: number) => {
                            const citeMatch = part.match(/\[(\d+)\]/);
                            if (citeMatch) {
                              const sourceId = parseInt(citeMatch[1]);
                              const source = report.sources?.find(s => s.id === sourceId);
                              const instanceKey = `${i}-${j}`; // unique per citation instance to prevent stacking
                              return (
                                <span
                                  key={j}
                                  className="relative inline"
                                  onMouseEnter={() => setHoveredCitation(instanceKey)}
                                  onMouseLeave={() => setHoveredCitation(null)}
                                >
                                  <sup className="text-my-accent font-bold text-[10px] cursor-help hover:underline relative">
                                    [{sourceId}]
                                  </sup>
                                  {source && (
                                    <EvidencePreview
                                      source={{
                                        id: source.id,
                                        title: source.title,
                                        url: source.url,
                                        domain: source.domain || '',
                                        type: source.type || 'web',
                                        snippet: source.key_finding || '',
                                        credibility_score: source.credibility_score || 0,
                                        relevance_score: source.relevance_score || 0,
                                        key_finding: source.key_finding || '',
                                        published_date: source.published_date || '',
                                        bias_flag: source.bias_flag || null,
                                        retrieval_timestamp: source.retrieval_timestamp || new Date().toISOString()
                                      }}
                                      isVisible={hoveredCitation === instanceKey}
                                    />
                                  )}
                                </span>
                              );
                            }
                            return part;
                          });
                        })()}
                      </p>
                    ) : <br key={i} />
                  )}
                </div>
              )}
              {report.summary?.confidence_narrative && (
                 <div className="flex items-start gap-2 p-3 bg-my-callout border border-my-border rounded mt-2">
                   <span className="text-[10px] font-bold text-my-accent uppercase tracking-widest shrink-0 mt-0.5">AI Self-Assessment</span>
                   <p className="italic text-my-muted text-[12px] leading-[1.6]">{safeText(report.summary.confidence_narrative)}</p>
                 </div>
              )}
            </div>
          )}

          {!readOnly && !report?.archive_entry?.tags?.includes('document') && (
            <>
              {/* Forensic Reasoning Replay — before sources */}
              <ThoughtReplayEngine />
            </>
          )}

          {/* Source Drawer */}
          {report.sources && report.sources.length > 0 && (
            <SourceDrawer 
              sources={report.sources.map((s: any) => ({
                ...s,
                snippet: s.key_finding || s.snippet || '',
                retrieval_timestamp: s.retrieval_timestamp || new Date().toISOString()
              }))}
              retrievalTrace={report._retrieval_trace || null}
            />
          )}

          {/* Actionable Takeaways — full width below the grid */}
          {report.actionable_takeaways && (
            <div className="border border-my-border bg-my-callout/50">
              <SectionTitle>Key Takeaways</SectionTitle>
              <div className="divide-y divide-my-border">
                <TakeawayCard title="Key Insight" content={report.actionable_takeaways.key_insight} />
                <TakeawayCard title="Watch Out For" content={report.actionable_takeaways.watch_out_for} />
                <TakeawayCard title="Next Step" content={report.actionable_takeaways.next_step} />
              </div>
            </div>
          )}
        </motion.div>

        <motion.div
          variants={{ hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0 } }}
          className="flex flex-col gap-6 min-w-0"
        >
          
          {/* Metrics */}
          <SectionTitle>Metrics</SectionTitle>
          {report.scores && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-[1px] bg-my-border border border-my-border">
               <ScoreCard label="Credibility" value={safeText(report.scores.overall_credibility)} />
               <ScoreCard label="Relevance" value={safeText(report.scores.overall_relevance)} />
               <div className="bg-my-callout p-3 flex flex-col justify-center col-span-2">
                 <span className="text-[9px] font-bold text-my-muted uppercase mb-1">Consensus</span>
                 <span className="text-my-ink font-semibold capitalize text-[13px]">{safeText(report.scores.evidence_consensus)}</span>
               </div>
            </div>
          )}

          {/* Contradictions Panel */}
          {hasConflicts && (
            <div className="border border-my-border bg-my-callout/50">
              <div className="w-full px-4 py-3 flex items-center justify-between border-b border-my-border/50">
                <div className="flex items-center gap-3">
                  <AlertTriangle size={14} className="text-red-500" />
                  <span className="text-[10px] font-bold uppercase tracking-widest text-my-ink">
                    Contradictions ({report.conflicts!.length})
                  </span>
                </div>
              </div>
              <div className="px-4 pb-4 space-y-3">
                {report.conflicts!.map((c, i) => (
                  <div key={i} className="border border-red-200 dark:border-red-900/40 bg-my-bg/50">
                    {/* Side-by-side claims */}
                    <div className="grid grid-cols-2 divide-x divide-red-200 dark:divide-red-900/40">
                      <div className="p-3">
                        <div className="flex items-center gap-1.5 mb-1.5">
                          <span className="w-1.5 h-1.5 rounded-full bg-red-500 shrink-0" />
                          <span className="text-[8px] font-black uppercase tracking-widest text-red-600 dark:text-red-400">Claim A</span>
                        </div>
                        <p className="text-[11px] leading-relaxed text-my-ink">{c.claim_a}</p>
                        <span className="text-[9px] font-mono text-my-muted mt-1.5 block">Source: {c.source_a}</span>
                      </div>
                      <div className="p-3">
                        <div className="flex items-center gap-1.5 mb-1.5">
                          <span className="w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0" />
                          <span className="text-[8px] font-black uppercase tracking-widest text-amber-600 dark:text-amber-400">Claim B</span>
                        </div>
                        <p className="text-[11px] leading-relaxed text-my-ink">{c.claim_b}</p>
                        <span className="text-[9px] font-mono text-my-muted mt-1.5 block">Source: {c.source_b}</span>
                      </div>
                    </div>
                    {/* Explanation */}
                    <div className="px-3 py-2.5 bg-red-50/50 dark:bg-red-950/20 border-t border-red-200 dark:border-red-900/40">
                      <span className="text-[8px] font-black uppercase tracking-widest text-my-muted block mb-1">Analysis</span>
                      <p className="text-[11px] leading-relaxed text-my-syn">{c.explanation}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* SWOT Analysis */}
          {report.swot && (
            <div className="border border-my-border bg-my-callout/50">
              <SectionTitle>Strategic Analysis</SectionTitle>
              {report.swot.perspective && (
                <div className="px-4 py-2 text-[9px] text-my-muted font-mono border-b border-my-border/50">
                  Perspective: {report.swot.perspective}
                </div>
              )}
              <div className="grid grid-cols-2 gap-[1px] bg-my-border">
                <SwotQuadrant title="Strengths" items={report.swot.strengths} />
                <SwotQuadrant title="Weaknesses" items={report.swot.weaknesses} />
                <SwotQuadrant title="Opportunities" items={report.swot.opportunities} />
                <SwotQuadrant title="Threats" items={report.swot.threats} />
              </div>
            </div>
          )}

          {/* Intelligence Map */}
          {report.intelligence_map && report.intelligence_map.central_node && Array.isArray(report.intelligence_map.nodes) && report.intelligence_map.nodes.length > 0 && (
            <div className="mt-6 lg:mt-0">
              <SectionTitle>Intelligence Map</SectionTitle>
              <div className="mt-3">                  <ErrorBoundary fallback={<div className="h-48 flex items-center justify-center text-my-muted text-[10px] uppercase tracking-widest bg-my-callout/50 rounded-[4px] border border-my-border">Semantic graph unavailable</div>}>
                 <Suspense fallback={<div className="h-48 flex items-center justify-center text-my-muted animate-pulse text-[10px] uppercase tracking-widest bg-my-callout/50 rounded-[4px] border border-my-border">Loading semantic graph...</div>}>
                   <PhysicsMap mapData={report.intelligence_map} onSubSearch={readOnly ? () => {} : onSubSearch} readOnly={readOnly} />
                 </Suspense>
               </ErrorBoundary>
              </div>
            </div>
          )}

        </motion.div>
      </motion.div>

      {/* Follow-ups */}
      {!readOnly && normalizedSuggestions && normalizedSuggestions.length > 0 && (
        <div className="pt-6 mt-8 border-t border-my-border">
          <SectionTitle>Investigate Further</SectionTitle>
          <div className="flex flex-wrap gap-2 mt-3">
            {normalizedSuggestions.map((f: string, i: number) => (
              <button 
                key={i} 
                onClick={() => !readOnly && (onChatFollowUp ? onChatFollowUp(f) : onSubSearch(f))}
                disabled={readOnly}
                className="bg-my-bg border border-my-border hover:border-my-accent text-[12px] text-my-ink py-2.5 md:py-1.5 px-3 transition-colors flex items-center gap-2"
              >
                {safeText(f)} <ArrowRight size={12} className="opacity-50" />
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Feedback */}
      {report.feedback_prompt && !rated && (
         <div className="mt-8 flex justify-center py-4 border-t border-b border-my-border">
           <div className="flex items-center gap-4 text-xs tracking-wide text-my-ink font-bold">
             <span>{safeText(report.feedback_prompt)}</span>
             <div className="flex items-center gap-1">
               {[1,2,3,4,5].map(i => (
                 <button key={i} onClick={() => handleRating(i)} className="hover:scale-125 transition-transform text-lg grayscale hover:grayscale-0 cursor-pointer">⭐</button>
               ))}
             </div>
           </div>
        </div>
      )}
      {rated && (
        <div className="mt-8 flex items-center justify-center py-4 border-t border-my-border text-my-accent text-xs font-bold gap-2 animate-in fade-in zoom-in">
           <CheckCircle2 size={16} /> Thank you for your feedback! Data logged.
        </div>
      )}

      {/* AI Limitation Disclaimer */}
      <div className="mt-12 pt-6 border-t border-my-border">
        <div className="flex items-start gap-2 text-[10px] text-my-muted leading-[1.6]">
          <AlertTriangle size={10} className="text-amber-500 mt-0.5 shrink-0" />
          <p>
            <strong className="uppercase tracking-widest">AI-Generated Content:</strong> This report was produced by artificial intelligence systems. 
            Confidence scores, credibility ratings, and consensus metrics are derived from model self-assessment, not ground-truth validation. 
            <strong>Confidence does not equal certainty, and consensus does not equal factual truth.</strong> 
            Always independently verify critical claims, statistics, and citations before relying on them. 
            See the <a href="/policies" onClick={(e) => { e.preventDefault(); window.location.hash = 'ai-disclaimer'; }} className="underline hover:text-my-accent">AI Liability Disclaimer</a> for full details.
          </p>
        </div>
      </div>

      <PremiumExportModal 
        isOpen={isExportModalOpen}
        onClose={() => setIsExportModalOpen(false)}
        researchId={reportId}
        query={report.query_understood}
        onUnlockSuccess={handleDownloadPDF}
      />

      {/* Live Source Panel */}
      <AnimatePresence>
        {liveSource && (
          <motion.div
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'spring', damping: 25, stiffness: 200 }}
            className="fixed top-16 right-0 bottom-0 w-full sm:w-[480px] bg-my-bg border-l border-my-border shadow-2xl z-40 flex flex-col"
          >
            <div className="flex items-center justify-between px-4 py-3 border-b border-my-border">
              <div className="flex items-center gap-2 min-w-0">
                <ExternalLink size={12} className="text-my-accent shrink-0" />
                <span className="text-[10px] font-bold uppercase tracking-widest truncate">{liveSource.title}</span>
              </div>
              <button
                onClick={() => setLiveSource(null)}
                className="p-1 hover:bg-my-callout rounded-sm transition-colors"
              >
                <X size={14} />
              </button>
            </div>
            <div className="flex-1 flex flex-col">
              <div className="px-4 py-2 bg-my-callout border-b border-my-border flex items-center gap-2 text-[9px] text-my-muted font-mono">
                <AlertTriangle size={9} className="text-amber-500 shrink-0" />
                <span>If the page doesn't load, many sites block iframe embedding. Use the button below.</span>
              </div>
              <iframe
                src={liveSource.url}
                className="flex-1 w-full border-0"
                sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox"
                title={liveSource.title}
              />
              <div className="px-4 py-3 border-t border-my-border bg-my-callout flex items-center gap-3">
                <a
                  href={liveSource.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex-1 px-3 py-2 bg-my-accent text-white dark:text-black text-[9px] font-black uppercase tracking-widest text-center hover:opacity-90 transition-opacity flex items-center justify-center gap-2"
                >
                  <ExternalLink size={10} /> Open in New Tab
                </a>
                <button
                  onClick={() => setLiveSource(null)}
                  className="px-3 py-2 border border-my-border text-[9px] font-bold uppercase tracking-widest text-my-muted hover:text-my-ink transition-colors"
                >
                  Close
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-[10px] uppercase tracking-[0.1em] font-bold text-my-muted border-b border-my-border pb-1">
      {children}
    </div>
  );
}

function ScoreCard({ label, value }: { label: string, value: any }) {
  const num = typeof value === 'string' ? parseFloat(value) : value;
  const displayValue = typeof num === 'number' && !isNaN(num) ? num.toFixed(1) + '%' : value;
  return (
    <div className="bg-my-callout p-3 flex flex-col justify-center">
      <span className="text-[9px] font-bold text-my-muted uppercase mb-1">{label}</span>
      <span className="text-my-accent font-bold text-lg leading-none">{displayValue}</span>
    </div>
  );
}

function TakeawayCard({ title, content }: { title: string, content: string }) {
  return (
    <div className="bg-my-callout p-3">
      <h4 className="font-bold text-[9px] uppercase tracking-wide mb-1.5 text-my-muted">
        {title}
      </h4>
      {content?.trim() ? (
        <p className="text-[12px] leading-[1.5] text-my-ink font-medium">{content}</p>
      ) : (
        <p className="text-[10px] text-my-border italic">N/A</p>
      )}
    </div>
  );
}

function SwotQuadrant({ title, items }: { title: string, items: string[] }) {
  if (!items || !Array.isArray(items) || items.length === 0) return (
    <div className="bg-my-callout p-3">
      <h4 className="font-bold text-[9px] uppercase tracking-wide text-my-muted">{title}</h4>
      <div className="text-[10px] text-my-border mt-2">N/A</div>
    </div>
  );
  return (
    <div className="bg-my-callout p-3 flex flex-col">
      <h4 className="font-bold text-[9px] uppercase tracking-wide mb-1 text-my-muted">{title}</h4>
      <div className="flex flex-col gap-1 mt-1">
        {items.map((item, i) => (
          <div key={i} className="text-[12px] leading-[1.5] text-my-ink">
            • {typeof item === 'object' && item !== null ? JSON.stringify(item) : item}
          </div>
        ))}
      </div>
    </div>
  );
}
