import React from 'react';
import { Scale, AlertTriangle, ShieldAlert, FileText, Gavel } from 'lucide-react';

export default function LegalDocs() {
  return (
    <div className="space-y-16 animate-in fade-in slide-in-from-bottom-4 duration-700 fill-mode-forwards">
      
      {/* Overview Section */}
      <section id="legal-overview" className="scroll-mt-32 space-y-8">
        <div>
          <div className="flex items-center gap-3 text-my-accent font-bold uppercase tracking-[0.4em] text-[10px] mb-4">
            <div className="w-10 h-px bg-my-accent" /> Section_05
          </div>
          <h2 className="text-4xl md:text-5xl font-serif font-bold italic text-my-ink mb-6">Legal & Compliance</h2>
          <p className="text-xl font-light leading-relaxed text-my-muted max-w-3xl">
            By accessing the COGNAPSE platform, you agree to the following terms and policies regarding platform usage, data handling, and liability.
          </p>
        </div>
      </section>

      {/* AI Liability Disclaimer */}
      <section id="ai-disclaimer" className="scroll-mt-32 space-y-8 border-t border-my-border pt-16">
         <div className="flex items-center gap-3">
           <AlertTriangle className="text-red-500" size={28} />
           <h3 className="text-2xl font-bold text-my-ink border-b border-my-border pb-2 flex-1">Generative AI Disclaimer</h3>
         </div>
         
         <div className="p-8 border border-red-500/30 bg-red-500/5 rounded-sm space-y-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10">
               <Gavel size={100} />
            </div>
            <p className="text-sm text-my-muted leading-relaxed font-semibold">
             <p className="text-sm text-my-muted leading-relaxed font-semibold">
               <strong className="text-red-400 uppercase tracking-widest">1. Experimental Technology:</strong> COGNAPSE utilizes Large Language Models (LLMs). While the platform is designed to assist with research and information synthesis, the underlying technology is statistical and may produce inaccurate, incomplete, or misleading information (commonly known as "hallucinations").
             </p>
            </p>
            <p className="text-sm text-my-muted leading-relaxed font-semibold">
              <strong className="text-red-400 uppercase tracking-widest">2. Not Professional Advice:</strong> The information generated by COGNAPSE is for research and informational purposes only. It should not be construed as financial, medical, legal, or professional advice. Users should consult qualified professionals before making decisions based on platform output.
            </p>
            <p className="text-sm text-my-muted leading-relaxed font-semibold">
              <strong className="text-red-400 uppercase tracking-widest">3. Limitation of Liability:</strong> By using the platform, you agree that COGNAPSE and its operators are not liable for any direct, indirect, or consequential damages resulting from your use of or reliance on the generated information. Users are responsible for verifying all factual claims independently.
            </p>
         </div>
      </section>

      {/* Terms of Service */}
      <section id="terms" className="scroll-mt-32 space-y-8 border-t border-my-border pt-16">
         <div className="flex items-center gap-3">
           <FileText className="text-my-ink" size={24} />
           <h3 className="text-2xl font-bold text-my-ink border-b border-my-border pb-2 flex-1">Terms of Service Excerpts</h3>
         </div>
         
         <div className="space-y-6">
            <div className="p-6 border border-my-border bg-my-sidebar/10">
               <h4 className="text-sm font-bold text-my-ink mb-2 uppercase tracking-widest">Third-Party Service Dependencies</h4>
               <p className="text-xs text-my-muted leading-relaxed">
                 The application's functionality relies on third-party APIs (such as Groq and Google Gemini). Service availability is subject to the operational status of these providers. COGNAPSE is not responsible for platform downtime resulting from third-party outages, rate limits, or API deprecations.
               </p>
            </div>

            <div className="p-6 border border-my-border bg-my-sidebar/10">
               <h4 className="text-sm font-bold text-my-ink mb-2 uppercase tracking-widest">Payments, Subscriptions, & Refunds</h4>
               <p className="text-xs text-my-muted leading-relaxed mb-3">
                 All financial transactions for Premium access (Monthly or Annual passes) are processed securely through a third-party payment gateway (Razorpay). COGNAPSE does not directly store or process credit card information. We are not liable for any payment processing errors, unauthorized charges, or data breaches occurring at the payment processor level.
               </p>
               <p className="text-xs text-my-muted leading-relaxed">
                 <strong className="text-my-accent">Refund Policy:</strong> All subscription payments are final and non-refundable unless otherwise mandated by applicable law. Cancellation of a subscription will prevent future billing, but no prorated refunds will be issued for the current billing cycle.
               </p>
            </div>

            <div className="p-6 border border-my-border bg-my-sidebar/10">
               <h4 className="text-sm font-bold text-my-ink mb-2 uppercase tracking-widest">Data Management</h4>
               <p className="text-xs text-my-muted leading-relaxed">
                 COGNAPSE utilizes local browser storage (IndexedDB) as its primary data persistence mechanism. While cloud synchronization is available, COGNAPSE is not liable for data loss resulting from users clearing browser data, hardware failure, or synchronization conflicts across devices.
               </p>
            </div>

            <div className="p-6 border border-my-border bg-my-sidebar/10">
               <h4 className="text-sm font-bold text-my-ink mb-2 uppercase tracking-widest">User Content Guidelines</h4>
               <p className="text-xs text-my-muted leading-relaxed">
                 Users are solely responsible for any content they generate and share using the platform. You agree not to use COGNAPSE to generate or distribute illegal, defamatory, or copyright-infringing material. Users agree to indemnify COGNAPSE against claims arising from their use of the platform's sharing features.
               </p>
            </div>
         </div>
      </section>

      {/* Privacy Policy */}
      <section id="privacy" className="scroll-mt-32 space-y-8 border-t border-my-border pt-16">
         <div className="flex items-center gap-3">
           <ShieldAlert className="text-emerald-500" size={24} />
           <h3 className="text-2xl font-bold text-my-ink border-b border-my-border pb-2 flex-1">Privacy Policy Overview</h3>
         </div>
         
         <div className="prose prose-sm prose-invert max-w-none text-my-muted">
            <p>
              COGNAPSE follows a privacy-first methodology regarding user data collection and processing.
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-4 marker:text-my-accent">
               <li><strong>Data Collection:</strong> We collect only the information necessary to provide authentication services (e.g., email addresses via Firebase Auth). We do not sell user data or search histories to third parties.</li>
               <li><strong>Data Usage:</strong> User-generated queries and documents are processed to fulfill the user's immediate request. We do not use private user data to train our foundational models.</li>
               <li><strong>Local Processing:</strong> Certain features, such as claim verification, process data locally on the user's device via WebAssembly to minimize data transmission.</li>
               <li><strong>Data Deletion:</strong> Users have the right to request the deletion of their account and associated data. Initiating account deletion from the application interface will permanently remove data from our active databases.</li>
            </ul>
         </div>
      </section>

    </div>
  );
}
